# Generated by Django 3.1.2 on 2020-10-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='-', max_length=200)),
                ('content', models.TextField(default='-')),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
