# Generated by Django 3.1.2 on 2020-10-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(default='-', max_length=200)),
                ('done', models.TextField(default=False)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
