# Generated by Django 3.1.2 on 2020-10-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='activity',
            field=models.TextField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='todo',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
